config/routes.rb
BackboneContacts::Application.routes.draw do

  get 'contacts/all'
  resources :contacts

  root :to => 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :email, :name, :photo, :tel, :type
  self.inheritance_column = 'inheritance_type'

  #Override as_json to format json response in a particular way.
  #http://stackoverflow.com/questions/2572284/how-to-override-to-json-in-rails
  def as_json(options ={})
    super(options.merge(only: [:id, :address, :email, :name, :photo, :tel, :type]))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/all
  # gets all the contacts in json format.
  def all
    render json: Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
    <div class="brand">Contacts App</div>
    </div>
  </div>
</div>

<div class="container">
  <div id="contacts" class="row">
    <div class="offset3 span6">
      <div id="sticky-anchor"></div>
      <div id="sticky" class="well span6">
        <div class="row topspacing">
          <div class="span2 textalignright">
            <a href="#addContact" role="button" data-toggle="modal" class="btn"><i class="icon-plus"></i>&nbsp;&nbsp;New Contact</a>
          </div>
          <div class="span1 textalignright">
            <label>Filter:</label>
          </div>
          <div class="span3">
                  <div id="filter">
                    <label>Show me:</label>
                  </div>
          </div>
        </div>       
        <!-- Form to add a new contact -->
        <form id="addContact" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <!--NOTE!: make sure id attributes match the attributes of the contact model.
      Makes life easier that way -->
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Modal header</h3>
          </div>
          <div class="modal-body">
            <div class="control-group">
              <label class="control-label" for="photo">Photo:</label>
              <div class="controls">
                <input id="photo" type="file" disabled="disabled"/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label"  for="type">Type:</label>
              <div class="controls">
                <input id="type" type="text"/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label"  for="name">Name:</label>
              <div class="controls">
                <input id="name" type="text"/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label"  for="address">Address:</label>
              <div class="controls">
                <input id="address" type="text"/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label"  for="tel">Tel:</label>
              <div class="controls">
                <input id="tel" type="text"/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label"  for="email">Email:</label>
              <div class="controls">
                <input id="email" type="text" />
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="add" class="btn btn-primary">Add</button>
            <!--<button class="btn btn-primary">Save changes</button>-->
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


<!-- If you have jQuery directly, then skip next line -->
<script src="http://www.google.com/jsapi"></script>

<script type="text/javascript">
  // If you have jQuery directly, then skip next line
  //google.load("jquery", "1");

  function sticky_relocate() {
    var window_top = $(window).scrollTop();
    var div_top = $('#sticky-anchor').offset().top;
    if (window_top > div_top)
      $('#sticky').addClass('stick')
    else
      $('#sticky').removeClass('stick');
    }
  // If you have jQuery directly, use the following line, instead
  // $(function() {
  // If you have jQuery via Google AJAX Libraries
  google.setOnLoadCallback(function() {
    $(window).scroll(sticky_relocate);
    sticky_relocate();
    });
</script>

<!-- Contact template
The {{ }} will be replace by the attributes of a Contact model -->
<!-- Use custom "type" attribute so the browser doesn't try to execute it
without a custom type it will think that it is javascript to execute -->
<script id="contactTemplate" type="text/template">
  <div class="well">
    <div class="clearfix">
    <img src="{{ photo }}" alt="{{ name }}" />
    <h1>{{ name }}</h1>
    <div>{{ address }}</div>
    </div>
    <dl>
      <dt>Type:</dt><dd>{{type}}</dd>
      <dt>Tel:</dt><dd>{{ tel }}</dd>
      <dt>Email:</dt><dd><a href="mailto:{{ email}}">{{ email }}</a></dd>
    </dl>
    <div class="edit-buttons">
      <button class="btn btn-primary edit">Edit</button>
      <button class="btn delete">Delete</button>
    </div>
  </div>
</script>

<!-- Edit contact template -->
<script id="contactEditTemplate" type="text/template">
  <div class="well">
    <form action="#">
      <input type="file" value="{{ photo }}" disabled="disabled"/>
      <input type="text" class="name" value="{{ name }}" placeholder="Name" />
      <input id="type" type="hidden" value="{{ type }}" />
      <input type="text" class="address" value="{{ address }}" placeholder="Address"/>
      <input type="text" class="tel" value="{{ tel }}" placeholder="Telephone #"/>
      <input type="text" class="email" value="{{ email }}" placeholder="Email"/>
      <div>
        <button class="btn btn-primary save">Save</button>
        <button class="btn cancel">Cancel</button>
      </div>
    </form>
  </div>
</script>

<script type="text/javascript">
  var placeHolderImagePath = "<%= asset_path 'placeholder.png' %>";
  var contacts = <%= @contacts.to_json.html_safe %>;
  var contact = <%= @contacts[0].to_json.html_safe %>;
</script>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Photo:</b>
  <%= @contact.photo %>
</p>

<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Address:</b>
  <%= @contact.address %>
</p>

<p>
  <b>Tel:</b>
  <%= @contact.tel %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Type:</b>
  <%= @contact.type %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackboneContacts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>